server:
  port: 8082

spring:
  session:
    store-type: redis

logging:
  level:
    com.example: DEBUG
    org.springframework.data: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
